# Generated by Django 3.2.6 on 2022-07-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_answer', '0002_answer_question_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='which_subject',
            name='avatar',
            field=models.ImageField(default='bg.png', upload_to='avatars/'),
        ),
    ]
